POSWeb.IU/Controllers/FacturacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POSWeb.IU.Servicio;
using POSWeb.ControlExcepciones;
using POSWeb.Entidades;

namespace POSWeb.IU.Controllers
{
    public class FacturacionController : Controller
    {
        CnnWebApi servicio = new CnnWebApi();

        // GET: Facturacion
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult BuscarProducto(string codigoBarra)
        {
            var respuesta = new RespuestaProducto();
            try
            {
                //****envíamos a buscar el producto
                respuesta = servicio.ObtenerProductoPorCodigo(codigoBarra);
                //****

                //respuesta exitosa
                return Json(new
                {
                    CodError = respuesta.Respuesta.CodMensaje,
                    Data = respuesta.Producto
                });
            }
            catch (Exception ex)
            {
                //registra error
                ControlExcepciones.ControlExcepciones.ManejoExcepciones(ex, codigoBarra);

                //respuesta error
                return Json(new
                {
                    CodError = Respuesta.CodNoValido
                });
            }
            //prueba
        }
    }
}

POSWeb.IU/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POSWeb.IU.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

POSWeb.IU/Views/Facturacion/Index.cshtml
@model POSWeb.Entidades.Producto
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="small-header">
    <div class="hpanel">
        <div class="panel-body">
            <div id="hbreadcrumb" class="pull-right">
                <ol class="hbreadcrumb breadcrumb">
                    <li>@Resources.TextosVistas.POSWeb</li>
                    <li class="active">
                        <span>@Resources.TextosVistas.Facturacion </span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                @Resources.TextosVistas.Facturacion
            </h2>
            <small>@Resources.TextosVistas.txtFacturacionDesc</small>
        </div>
    </div>
</div>


<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form role="form" id="form">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CodigoBarra)
                            @Html.TextBoxFor(model => model.CodigoBarra, htmlAttributes: new { @placeholder = "Código Producto", required = "required", @class="form-control" })
                            @*<input type="text" placeholder="Código Producto" class="form-control" required>*@
                        </div>
                        <div>
                            <button class="btn btn-sm btn-primary m-t-n-xs" type="button" onclick="oFacturacion.BuscarProducto();"><strong>Submit</strong></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="hpanel">
                <div class="panel-heading">
                    Items de Compra
                </div>
                <div class="panel-body">

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Cantidad</th>
                                <th>Producto</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input type="text" name="name" value="1" /></td>
                                <td>Coca Cola Zero 2 L</td>
                                <td>2500</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Imperial 600 ml</td>
                                <td>2000</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Chocolate Tutto</td>
                                <td>1500</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="hpanel">
                <div class="panel-heading">
                    Resumen de Compra
                </div>
                <div class="panel-body">
                    <div class="form-group"><label>Total a pagar: ₡ 6,000</label></div>
                    <div class="form-group"><button class="btn btn-sm btn-primary m-t-n-xs" type="button">Pagar</button></div>
                    <div class="form-group"><button class="btn btn-sm btn-primary m-t-n-xs" type="button">Cancelar</button></div>
                </div>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/validation/js")
    @Scripts.Render("~/Scripts/EventosFormulario/EventosFacturacion.js")
    <script type="text/javascript">
        var urlBuscarProducto = '@Url.Action("BuscarProducto", "Facturacion")';

          $(function(){

        $("#form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 3
                },
                url: {
                    required: true,
                    url: true
                },
                number: {
                    required: true,
                    number: true
                },
                max: {
                    required: true,
                    maxlength: 4
                }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });

    </script>
}

POSWeb.IU/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

POSWeb.IU/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

POSWeb.IU/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

POSWeb.IU/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        @Resources.TextosVistas.POSWeb
    </span>
    @Resources.TextosVistas.NombreCompania © @DateTime.Now.Year
</footer>

POSWeb.IU/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version">
    <span>
        @Resources.TextosVistas.POSWeb
    </span>
</div>
<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">@Resources.TextosVistas.POSWeb</span>
    </div>
    <form role="search" class="navbar-form-custom" method="post" action="#">
        @*<div class="form-group">
            <input type="text" placeholder="Busque algo especial" class="form-control" name="search">
        </div>*@
    </form>
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="" href="@Url.Action("Login", "CommonViews")">Login</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Register", "CommonViews")">Logout</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("ProfilePage", "AppViews")">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="navbar-right">
        <ul class="nav navbar-nav no-borders">
            @*<li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-speaker"></i>
                </a>
                <ul class="dropdown-menu hdropdown notification animated flipInX">
                    <li>
                        <a>
                            <span class="label label-success">NEW</span> It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-warning">WAR</span> There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-danger">ERR</span> Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See all notifications</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-keypad"></i>
                </a>
                <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Projects", "AppViews")">
                                        <i class="pe pe-7s-portfolio text-info"></i>
                                        <h5>Projects</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Mailbox", "AppViews")">
                                        <i class="pe pe-7s-mail text-warning"></i>
                                        <h5>Email</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Contacts", "AppViews")">
                                        <i class="pe pe-7s-users text-success"></i>
                                        <h5>Contacts</h5>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Forum", "AppViews")">
                                        <i class="pe pe-7s-comment text-info"></i>
                                        <h5>Forum</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "Analytics")">
                                        <i class="pe pe-7s-graph1 text-danger"></i>
                                        <h5>Analytics</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("FileManager", "AppViews")">
                                        <i class="pe pe-7s-box1 text-success"></i>
                                        <h5>Files</h5>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                    <i class="pe-7s-mail"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu hdropdown animated flipInX">
                    <div class="title">
                        You have 4 new messages
                    </div>
                    <li>
                        <a>
                            It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            Lorem Ipsum is simply dummy.
                        </a>
                    </li>
                    <li>
                        <a>
                            Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See All Messages</a></li>
                </ul>
            </li>*@
            @*<li>
                <a href="#" id="sidebar" class="right-sidebar-toggle">
                    <i class="pe-7s-upload pe-7s-news-paper"></i>
                </a>
            </li>*@

            @*Se comenta por el momento*@
            @*<li class="dropdown">
                <a href="@Url.Action("CambiarClave", "Usuario")" data-action="userLogout"><i class="fa fa-key"></i></a>
            </li>
            <li class="dropdown">
                <a href="@Url.Action("Logout", "account")" data-action="userLogout"><i class="fa fa-sign-out"></i></a>
            </li>*@
        </ul>
    </div>

</nav>

POSWeb.IU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>POS Web | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass() fixed-navbar fixed-sidebar fixed-footer fixed-small-header">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>POS Web</h1><p>El sistema puede tardar adaptandose para una mejor experiencia </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    <aside id="menu">
        @*@{ Html.RenderPartialIf("_Navigation", Request.IsAuthenticated); }*@
        @Html.Partial("_Navigation")
    </aside>

    <!-- Main view  -->
    <div id="wrapper">
        <div id="procesando">
            @*<img style="display: block; margin: auto auto auto auto;" src="@Url.Content(" ~/Images/cargando.gif")"/>*@
        </div>
        @RenderBody()
        <!-- Right Sidebar -->
        @Html.Partial("_Right_Sidebar")
        <!-- Footer-->
        @Html.Partial("_Footer")

        @*@if (Request.IsAuthenticated)
            {
            <!-- Right Sidebar -->
                @Html.Partial("_Right_Sidebar")
            <!-- Footer-->
                @Html.Partial("_Footer")
            }*@

    </div>

    <!-- Section for main scripts render -->
    @*@Scripts.Render("~/bundles/jquery/js")*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui/js");
    @Scripts.Render("~/bundles/bootstrap/js")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/homer/js")
    @Scripts.Render("~/bundles/utilitarios")
    @Scripts.Render("~/bundles/tinymce/js")


    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="~/Scripts/sweetalert2/sweetalert2.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/css/sweetalert2.css">



@{
    var Msj = "null"; var TipoMensaje = "null"; var Titulo = "null";
    if (ViewBag.TipoMensaje != null | ViewBag.Titulo != null | ViewBag.Msj != null)
    {
        Msj = ViewBag.Msj;
        TipoMensaje = ViewBag.TipoMensaje.ToString();
        Titulo = ViewBag.Titulo;
    }
    //ControllerName
    var ControllerName = "null"; var MsjEliminar = "null";
    if (ViewBag.ControllerName != null & ViewBag.MsjEliminar != null)
    {
        ControllerName = ViewBag.ControllerName;
        MsjEliminar = ViewBag.MsjEliminar;
    }

}
<script>
    var Msj = '@Html.Raw(HttpUtility.JavaScriptStringEncode(@Msj.ToString()))';
    var TipoMensaje = '@Html.Raw(HttpUtility.JavaScriptStringEncode(@TipoMensaje.ToString()))';
    var Titulo = '@Html.Raw(HttpUtility.JavaScriptStringEncode(@Titulo.ToString()))';

    var validaMsj = '@Html.Raw(HttpUtility.JavaScriptStringEncode(@MsjEliminar))';
    var msjEliminarDato = '@Html.Raw(HttpUtility.JavaScriptStringEncode(@MsjEliminar.ToString()))';

     //var mensajeRecursos = @Html.Raw(ViewBag.mensajeRecursos);
</script>
<script src="~/Scripts/UtilsSiteFunctions.js"></script>
@*<script src="~/Scripts/Utilidades/Utilitarios.js"></script>*@

POSWeb.IU/Views/Shared/_Right_Sidebar.cshtml
<div id="right-sidebar" class="animated fadeInRight">

    <div class="p-m">
        <button id="sidebar-close" class="right-sidebar-toggle sidebar-button btn btn-default m-b-md">
            <i class="pe pe-7s-close"></i>
        </button>
        <div>
            <span class="font-bold no-margins"> Analytics </span>
            <br>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        </div>
        <div class="row m-t-sm m-b-sm">
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">300,102</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">280,200</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
        </div>
        <div class="progress m-t-xs full progress-small">
            <div style="width: 25%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar"
                 class=" progress-bar progress-bar-success">
                <span class="sr-only">35% Complete (success)</span>
            </div>
        </div>
    </div>
    <div class="p-m bg-light border-bottom border-top">
        <span class="font-bold no-margins"> Social talks </span>
        <br>
        <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        <div class="m-t-md">
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a1.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">John Novak</span>
                        <small class="text-muted">21.03.2015</small>
                        <div class="social-content small">
                            Injected humour, or randomised words which don't look even slightly believable.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a3.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Mark Smith</span>
                        <small class="text-muted">14.04.2015</small>
                        <div class="social-content">
                            Many desktop publishing packages and web page editors.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a4.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Marica Morgan</span>
                        <small class="text-muted">21.03.2015</small>

                        <div class="social-content">
                            There are many variations of passages of Lorem Ipsum available, but the majority have
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="p-m">
        <span class="font-bold no-margins"> Sales in last week </span>
        <div class="m-t-xs">
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$170,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$580,90 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$620,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$140,70 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
        </div>
        <small>
            Lorem Ipsum is simply dummy text of the printing simply all dummy text.
            Many desktop publishing packages and web page editors.
        </small>
    </div>

</div>